// Public API exports for backend integration
export {
  WordTimestampSchema,
  CaptionSegmentSchema,
  HighlightModeSchema,
  WordEntryAnimationSchema,
  CaptionStyleSchema,
  VideoInputSchema,
  VideoNoneSchema,
  VideoFileSchema,
  VideoUrlSchema,
  SettingsSchema,
  RenderRequestSchema,
  RenderResponseSchema,
  SuccessResponseSchema,
  ErrorResponseSchema,
  QueuedResponseSchema,
  ProcessingResponseSchema,
  WebhookConfigSchema,
  HealthResponseSchema,
  type WordTimestamp,
  type CaptionSegment,
  type HighlightMode,
  type WordEntryAnimation,
  type CaptionStyle,
  type VideoInput,
  type Settings,
  type RenderRequest,
  type RenderResponse,
  type SuccessResponse,
  type ErrorResponse,
  type QueuedResponse,
  type ProcessingResponse,
  type WebhookConfig,
  type HealthResponse
} from './api-contract.js';

// Platform API exports (multi-tenant, assets, templates, automations)
export {
  ProjectStatusSchema,
  ApiKeySchema,
  ProjectSettingsSchema,
  ProjectSchema,
  AssetTypeSchema,
  AssetStatusSchema,
  AssetSchema,
  TemplateSchema,
  AutomationTriggerSchema,
  AutomationActionSchema,
  AutomationSchema,
  AutomationRunSchema,
  CreateProjectRequestSchema,
  UpdateProjectRequestSchema,
  CreateApiKeyRequestSchema,
  CreateApiKeyResponseSchema,
  CreateAssetRequestSchema,
  CreateAssetResponseSchema,
  ListAssetsQuerySchema,
  CreateTemplateRequestSchema,
  UpdateTemplateRequestSchema,
  CreateAutomationRequestSchema,
  UpdateAutomationRequestSchema,
  TriggerAutomationRequestSchema,
  PlatformErrorCodeSchema,
  type ProjectStatus,
  type ApiKey,
  type ProjectSettings,
  type Project,
  type AssetType,
  type AssetStatus,
  type Asset,
  type Template,
  type AutomationTrigger,
  type AutomationAction,
  type Automation,
  type AutomationRun,
  type CreateProjectRequest,
  type UpdateProjectRequest,
  type CreateApiKeyRequest,
  type CreateApiKeyResponse,
  type CreateAssetRequest,
  type CreateAssetResponse,
  type ListAssetsQuery,
  type CreateTemplateRequest,
  type UpdateTemplateRequest,
  type CreateAutomationRequest,
  type UpdateAutomationRequest,
  type TriggerAutomationRequest,
  type PlatformErrorCode
} from './platform-contract.js';

export {createServer, startServer} from './server/index.js';
export {sendWebhook, wouldSendWebhook, type WebhookEvent} from './server/webhooks.js';

// Client SDK for backend integration
export {
  RenderowlClient,
  RenderowlError,
  type ClientOptions,
  type PollOptions,
  type RenderBuilder
} from './client/index.js';
